version: '3.9'

services:
  message:
    image: wisecat/chatwheel-update-service-message
    working_dir: /app
    ports:
      - '80:80'
      - '443:443'
    secrets:
      - NGINX_CONF_FULL_CHAIN_PEM
      - NGINX_CONF_PRIVATE_KEY_PEM
      - NGINX_CONF_SSL_DHPARAMS_PEM
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        window: 5s
    configs:
      - source: OPTIONS_SSL_NGINX_CONF
        target: /etc/nginx/options-ssl-nginx.conf

configs:
  OPTIONS_SSL_NGINX_CONF:
    external: true

secrets:

  NGINX_CONF_FULL_CHAIN_PEM:
    external: true

  NGINX_CONF_PRIVATE_KEY_PEM:
    external: true

  NGINX_CONF_SSL_DHPARAMS_PEM:
    external: true